log:
  file: ./app.log
  format: text
  level: 20
midi:
  path: ./midis
http:
  uri: http://localhost:8765/
#  uri: http://183.131.51.53:18998
websocket:
  enable: true
#  uri: ws://localhost:9999/admin/ws/info
  uri: ws://localhost:8765/rpc-control
  #  uri: ws://183.131.51.53:18998/rpc-control
  retry:
    max: 5
    delay: 5
